-- seed.sql
-- Data dummy siswa XI TKJ 3 (jalankan setelah schema.sql)
-- PERINGATAN: data ini untuk kebutuhan praktikum, bukan data pribadi resmi.

USE xi_tkj_3_profile;

-- Seed data siswa XI TKJ 3 (32 siswa, termasuk pengurus kelas)
INSERT INTO students (full_name, nickname, class_name, role_title, expertise, skills, interests, goals, description, photo_file) VALUES
('Aang Burhanudin Badsah', 'Aang', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Fotografi, Desain Grafis', 'Menjadi Penetration Tester profesional', 'Aang adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student1.jpg'),
('Adinda Ramadhani', 'Adinda', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Futsal, Membaca artikel teknologi', 'Membangun startup teknologi', 'Adinda adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student2.jpg'),
('Anantadewa Wiwasata Putra Maharani', 'Ananta', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Coding & Open Source, Robotika', 'Bekerja di divisi IT Security perusahaan besar', 'Ananta adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student3.jpg'),
('Annisa Ramadhani Putri Adiwanto', 'Annisa', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Desain Grafis, Musik', 'Menjadi System Administrator handal', 'Annisa adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student4.jpg'),
('Ariel Ardanta Nurrohman Reyhandy', 'Ariel', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Membaca artikel teknologi, Gaming & eSports', 'Melanjutkan kuliah Ilmu Komputer', 'Ariel adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student5.jpg'),
('Bima Gusto Mahatsafa', 'Bima', 'XI TKJ 3', 'Bendahara 1', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Robotika, Fotografi', 'Menjadi Network Engineer bersertifikat', 'Bima adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student6.jpg'),
('Byantara Al Hakim Nadhif', 'Byantara', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Musik, Futsal', 'Menjadi Penetration Tester profesional', 'Byantara adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student7.jpg'),
('Cleosya Kapita Bilqist', 'Cleo', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Gaming & eSports, Coding & Open Source', 'Membangun startup teknologi', 'Cleo adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student8.jpg'),
('Devina Aurelia Hapsari', 'Devina', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Fotografi, Desain Grafis', 'Bekerja di divisi IT Security perusahaan besar', 'Devina adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student9.jpg'),
('Ezar Brilliant Sugiono', 'Ezar', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Futsal, Membaca artikel teknologi', 'Menjadi System Administrator handal', 'Ezar adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student10.jpg'),
('Farhan Auliya Abrar', 'Farhan', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Coding & Open Source, Robotika', 'Melanjutkan kuliah Ilmu Komputer', 'Farhan adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student11.jpg'),
('Flavia Annisa Kurniawan', 'Flavia', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Desain Grafis, Musik', 'Menjadi Network Engineer bersertifikat', 'Flavia adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student12.jpg'),
('Gusti Putra Khakim Khaqiqi', 'Gusti', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Membaca artikel teknologi, Gaming & eSports', 'Menjadi Penetration Tester profesional', 'Gusti adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student13.jpg'),
('Hatta Muhlasin Luhtari', 'Hatta', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Robotika, Fotografi', 'Membangun startup teknologi', 'Hatta adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student14.jpg'),
('Intan Alshani Raffisya', 'Intan', 'XI TKJ 3', 'Bendahara 2', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Musik, Futsal', 'Bekerja di divisi IT Security perusahaan besar', 'Intan adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student15.jpg'),
('Iqbal Ilmi', 'Iqbal', 'XI TKJ 3', 'Sekretaris 1', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Gaming & eSports, Coding & Open Source', 'Menjadi System Administrator handal', 'Iqbal adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student16.jpg'),
('Ivander Ardell Alvaro', 'Ivander', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Fotografi, Desain Grafis', 'Melanjutkan kuliah Ilmu Komputer', 'Ivander adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student17.jpg'),
('Kenza Almira Yasmin', 'Kenza', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Futsal, Membaca artikel teknologi', 'Menjadi Network Engineer bersertifikat', 'Kenza adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student18.jpg'),
('M. Rafa Rizky E', 'Rafa', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Coding & Open Source, Robotika', 'Menjadi Penetration Tester profesional', 'Rafa adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student19.jpg'),
('Mochammad Davin Al Fida', 'Davin', 'XI TKJ 3', 'Ketua Kelas', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Desain Grafis, Musik', 'Membangun startup teknologi', 'Davin adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student20.jpg'),
('Muhammad Faris Anshori', 'Faris', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Membaca artikel teknologi, Gaming & eSports', 'Bekerja di divisi IT Security perusahaan besar', 'Faris adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student21.jpg'),
('Muhammad Hamizan Zuhri', 'Hamizan', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Robotika, Fotografi', 'Menjadi System Administrator handal', 'Hamizan adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student22.jpg'),
('Muhammad Kemal Faza', 'Kemal', 'XI TKJ 3', 'Wakil Ketua Kelas', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Musik, Futsal', 'Melanjutkan kuliah Ilmu Komputer', 'Kemal adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student23.jpg'),
('Muhammad Rifqi Nasywan Athallah', 'Rifqi', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Gaming & eSports, Coding & Open Source', 'Menjadi Network Engineer bersertifikat', 'Rifqi adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student24.jpg'),
('Nazriel Abiy Putra Veangga', 'Nazriel', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Fotografi, Desain Grafis', 'Menjadi Penetration Tester profesional', 'Nazriel adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student25.jpg'),
('Nizar Zulmi Firmansyah', 'Nizar', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Futsal, Membaca artikel teknologi', 'Membangun startup teknologi', 'Nizar adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student26.jpg'),
('Radine Dygtastya Rahmadhani', 'Radine', 'XI TKJ 3', 'Sekretaris 2', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Coding & Open Source, Robotika', 'Bekerja di divisi IT Security perusahaan besar', 'Radine adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student27.jpg'),
('Rahel Maryam', 'Rahel', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Desain Grafis, Musik', 'Menjadi System Administrator handal', 'Rahel adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student28.jpg'),
('Satria Banyu Seki', 'Satria', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Membaca artikel teknologi, Gaming & eSports', 'Melanjutkan kuliah Ilmu Komputer', 'Satria adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student29.jpg'),
('Valvizzy Piscesio Lois', 'Valvizzy', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Robotika, Fotografi', 'Menjadi Network Engineer bersertifikat', 'Valvizzy adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student30.jpg'),
('Yohan Alim Wijaya', 'Yohan', 'XI TKJ 3', 'Anggota', 'Network & System Administration', 'Mikrotik RouterOS, Linux Server, Subnetting & VLAN, DNS/DHCP', 'Musik, Futsal', 'Menjadi Penetration Tester profesional', 'Yohan adalah siswa  kelas XI TKJ 3 yang menekuni bidang Network & System Administration. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student31.jpg'),
('Ziyadatul Ilman Nafiah', 'Ziya', 'XI TKJ 3', 'Anggota', 'Cyber Security', 'Penetration Testing, Wireshark, OWASP Top 10, Linux Hardening', 'Gaming & eSports, Coding & Open Source', 'Membangun startup teknologi', 'Ziya adalah siswa  kelas XI TKJ 3 yang menekuni bidang Cyber Security. Aktif belajar dan berlatih di laboratorium jaringan dan keamanan siber sekolah.', 'student32.jpg');

-- Contoh komentar awal (stored XSS demo - JANGAN disanitasi di kode agar kerentanan tetap terlihat)
INSERT INTO comments (student_id, author_name, content) VALUES
(20, 'Wali Kelas', 'Selamat menjadi Ketua Kelas XI TKJ 3, semoga amanah!'),
(1, 'Teman Sekelas', 'Semangat terus belajar Network Administration ya!');
